<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>User Management</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>2422c171-bd50-475a-8c81-dd60d7ca1753</testSuiteGuid>
   <testCaseLink>
      <guid>3554e326-aaa3-4c0a-a31a-ad220cd64e35</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Registration</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>76b548da-701b-406b-9ee9-7c4c0a55e836</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Register</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>76b548da-701b-406b-9ee9-7c4c0a55e836</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>9cfacccd-c3b3-4a7e-96c3-b937b19789bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>76b548da-701b-406b-9ee9-7c4c0a55e836</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>e339e2fe-ce7d-463a-acf2-9d05db3da11e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>76b548da-701b-406b-9ee9-7c4c0a55e836</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>70c94cd6-d82c-40c3-8364-e4a32a286402</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>76b548da-701b-406b-9ee9-7c4c0a55e836</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Confirm_Password</value>
         <variableId>ce2c67f3-3622-4dab-b7f1-dc45780cdc46</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>365593db-6ec7-4780-a34f-7fb55ecaea2c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Profile Update</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>3aa53665-c1d7-495e-ad2b-357c482d46b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bed06aa8-f111-405f-ab5a-2a55f3c42a3f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>bed06aa8-f111-405f-ab5a-2a55f3c42a3f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>8a24573f-b0cc-411c-8b31-d9dde6d811ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bed06aa8-f111-405f-ab5a-2a55f3c42a3f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>e4eac892-e595-4534-91bf-c181608336b7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
