<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_REGISTER_center block smollMargin</name>
   <tag></tag>
   <elementGuidId>3ad33c3b-69ae-4a0a-a53f-060983565917</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.center.block.smollMargin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='registerPage']/article/sec-form/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c6c196de-c7a1-4bcc-82cd-0b8b507a2fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>center block smollMargin</value>
      <webElementGuid>a383d2e3-58ad-4ad2-88cc-8975c839ce69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-show</name>
      <type>Main</type>
      <value>!registerSuccess</value>
      <webElementGuid>cc58e73f-a92b-459b-9b41-df3ae202c2c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerPage&quot;)/article[1]/sec-form[@class=&quot;ng-isolate-scope secForm&quot;]/div[@class=&quot;center&quot;]/label[@class=&quot;center block smollMargin&quot;]</value>
      <webElementGuid>ab9bd840-527d-4077-96bb-e715028baba9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='registerPage']/article/sec-form/div[2]/label</value>
      <webElementGuid>6e29b14e-588e-4a75-b5aa-bc82837a22e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REGISTER'])[1]/following::label[1]</value>
      <webElementGuid>c0c44be7-a528-40d3-8672-ce014c6998ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I agree to the www.AdvantageOnlineShopping.com Conditions of Use and Privacy Notice'])[2]/following::label[1]</value>
      <webElementGuid>9d1a076a-5089-42b6-b84d-8662b19b2446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALREADY HAVE AN ACCOUNT?'])[1]/preceding::label[1]</value>
      <webElementGuid>4b783c64-f1cd-4bd2-9bda-b02755311e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi ,'])[1]/preceding::label[2]</value>
      <webElementGuid>d457cc0c-d91d-4598-8d0f-fc19ccba8c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>6b7c31ed-2a59-42ec-8958-04d303af4e53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
