<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>25869ab9-7fcd-4cd2-bde3-8a6b87c429c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.floatRigth.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myAccountContainer']/div/h3/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3a10ece2-6b50-4c14-8327-e330991b7f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floatRigth ng-scope</value>
      <webElementGuid>b240cd9a-48ae-4dca-9218-1d0bb9365adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/accountDetails</value>
      <webElementGuid>6cda1b51-cef7-4a12-bbf2-9d7817d27a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>3963baf7-2f1f-4238-853c-79fc7bafaa95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>8f66dde0-9910-4122-ae89-c16c88a18680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myAccountContainer&quot;)/div[@class=&quot;cube&quot;]/h3[@class=&quot;blueLink ng-binding&quot;]/a[@class=&quot;floatRigth ng-scope&quot;]</value>
      <webElementGuid>379931d8-fb67-4c62-86a4-9fc279f5a397</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myAccountContainer']/div/h3/a</value>
      <webElementGuid>0a960d22-119b-49c9-9ccc-f3a4e29e5170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit')]</value>
      <webElementGuid>c02b7b8a-4fc2-4570-a350-6091d887b8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MY ACCOUNT'])[2]/following::a[1]</value>
      <webElementGuid>b8ce0215-00cd-44a8-9b94-58118263edd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demo 12'])[1]/preceding::a[2]</value>
      <webElementGuid>cbad9313-116f-4316-beee-c77038f645d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Armenia'])[1]/preceding::a[2]</value>
      <webElementGuid>13847033-3b35-4345-95fd-647719fca2b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>be222ec0-08af-4325-bd19-09db74f06083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/accountDetails')]</value>
      <webElementGuid>f155090d-26f1-4d55-b136-1f741f0d965e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>183ab4ba-1d79-4f61-ac47-bda41e0bbdd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/accountDetails' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>69ee8a36-d179-4d89-bc25-5563eb67fc2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
