<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Armenia</name>
   <tag></tag>
   <elementGuidId>67a3d7f0-a988-433f-94f8-844ebb45b647</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myAccountContainer']/div/div/div[2]/label[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5268e0d5-16d8-469b-b352-21a914268bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-hide</name>
      <type>Main</type>
      <value>accountDetails.countryName == ''</value>
      <webElementGuid>7ce9e5e3-b158-4361-9be7-7dbf149e6ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>ba7210dc-a013-4972-b504-0a6e5b416794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Armenia </value>
      <webElementGuid>1942b41d-e56b-4d37-9378-c00bac9fbfc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myAccountContainer&quot;)/div[@class=&quot;cube&quot;]/div[@class=&quot;borderBox&quot;]/div[@class=&quot;middle&quot;]/label[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>84cb7f27-fbed-4639-874a-4742437fe132</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myAccountContainer']/div/div/div[2]/label[3]</value>
      <webElementGuid>e255acd9-7fca-459e-b320-504045198b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jakarta'])[1]/following::label[1]</value>
      <webElementGuid>365aabac-96ee-4e7c-aa43-9c7409fcb405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demo112 12'])[1]/following::label[3]</value>
      <webElementGuid>159fb248-e5c6-48e8-8a48-30c6d022436c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping details'])[1]/preceding::label[4]</value>
      <webElementGuid>fe313bd7-5af7-4441-8337-83736d2f0a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demo112 12'])[2]/preceding::label[4]</value>
      <webElementGuid>d0adba04-1b04-4c99-b9af-efd120f40599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Armenia']/parent::*</value>
      <webElementGuid>b68d9331-9769-43b0-beb6-d8ad3903ecdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label[3]</value>
      <webElementGuid>749b0185-da9b-4335-b784-c1f73540d290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' Armenia ' or . = ' Armenia ')]</value>
      <webElementGuid>057c7edd-442e-4926-9309-4916086c274b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
