<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CHECKOUT (1,488.00)</name>
   <tag></tag>
   <elementGuidId>984b6e1b-148d-434f-a88a-28fcb9663ca4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkOutButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='checkOutButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c1e6c467-1040-4c12-895e-1b95dedc379c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5adb2cea-9f1f-44b0-9c55-8a88ded5faab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-medium tami uft-class ng-binding</value>
      <webElementGuid>0a9b96e7-164d-4505-a73a-ae18b8543d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>checkout()</value>
      <webElementGuid>e0f8287b-696e-4cde-b142-661297dd4fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkOutButton</value>
      <webElementGuid>703eceeb-15f4-42f5-aca3-55bf2f1d5b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>check_out_btn</value>
      <webElementGuid>e3b32279-10a9-402f-a181-5e6ec2138a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHECKOUT ($1,488.00)</value>
      <webElementGuid>aefa4e96-5f49-4e8b-9c91-8b5aa2d3c3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkOutButton&quot;)</value>
      <webElementGuid>a84f9d3b-0d86-4b08-ba6a-a0173d49f612</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='checkOutButton']</value>
      <webElementGuid>bace3df4-935f-4322-b3ce-2d2a4b3f210c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shoppingCart']/table/tfoot/tr[2]/td/button</value>
      <webElementGuid>c3fe31b3-aa27-404d-a0d2-49efc188d9ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1,488.00'])[2]/following::button[1]</value>
      <webElementGuid>45eb6beb-17f1-4416-9760-d2408b10f3cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOTAL:'])[1]/following::button[1]</value>
      <webElementGuid>f009a217-fc75-45f8-970f-d246aa448af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your shopping cart is empty'])[2]/preceding::button[1]</value>
      <webElementGuid>0f1808c8-d0c3-4840-8061-652fdb8f6e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUE SHOPPING'])[1]/preceding::button[1]</value>
      <webElementGuid>bc4f974d-1885-4d56-a77e-f5b29af480c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/table/tfoot/tr[2]/td/button</value>
      <webElementGuid>1711d489-45d9-4f4c-80bb-831637b3ede3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'checkOutButton' and @name = 'check_out_btn' and (text() = 'CHECKOUT ($1,488.00)' or . = 'CHECKOUT ($1,488.00)')]</value>
      <webElementGuid>45be9b39-ac0e-4697-803c-261f28d876c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
