<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checklist Headphone</name>
   <tag></tag>
   <elementGuidId>36f375c4-a677-4f37-b66a-014f271183b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='category'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5296238-48a8-4bbb-9394-2ffe2510e0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>b503c89f-2626-40d9-81d2-19200814686d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8c0b3335-cb8c-405e-a6e7-8b4b289b7b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>categ.checked</value>
      <webElementGuid>21c4c8de-17dd-4a39-9430-0ba1388e24c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>includeProducts(categ.id, 'CATEGORIES')</value>
      <webElementGuid>8c67aade-beca-4e70-9e1e-2b852195ba0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-touched</value>
      <webElementGuid>4cafdf46-24da-45dc-a6e2-cbe5c141751a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobileSlide&quot;)/ul[1]/li[@class=&quot;ng-scope&quot;]/div[@class=&quot;option&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;fill&quot;]/input[@class=&quot;ng-pristine ng-valid ng-touched&quot;]</value>
      <webElementGuid>b19e722e-5049-4d27-99b7-926d27e593a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='category'])[2]</value>
      <webElementGuid>5391c00b-eb04-4704-acb9-3eea18b03e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobileSlide']/ul/li/div/div[2]/div/input</value>
      <webElementGuid>db28905a-433f-4552-ab07-c730d7b33a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>c97864a3-4aa3-4273-9477-6fe95a14a951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'category' and @type = 'checkbox']</value>
      <webElementGuid>82ad8d49-c7f0-4981-b1b5-0cc3cd508c2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
